sudo: required

env:
  - BUILD_TYPE=Release

dist: xenial

services:
  - docker

compiler:
- gcc

notifications:
  email: false

language: C++

before_install:

script:
- mkdir dealii
- cd dealii
- git clone https://github.com/dealii/dealii.git
- mkdir build
- cd build
- cmake ../dealii
- make -j16
