sudo: required
language: cpp

notifications:
  email: false
  webhooks: https://www.travisbuddy.com/

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

before_script:
    docker pull heltai/dealii:v9.1.1-gcc-mpi

script:
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
- docker run heltai/dealii:v9.1.1-gcc-mpi /bin/sh -c "git clone https://github.com/SGauvin/lethe && cd lethe && git checkout $BRANCH && mkdir build && cd build && cmake ../ -DCMAKE_BUILD_TYPE=Release && make -j2 && ctest -j2 --verbose"
