language: cpp

os: linux

notifications:
  email: false
  webhooks: https://www.travisbuddy.com/

addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

matrix:
  include:
    - name: Static checks (clang-format)
      stage: check
      env: STATIC_CHECKS=yes
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-8
          packages:
            - clang-format-8

    - name: Compile and ctest
      stage: build
      env: COMPILE_AND_TEST=yes

before_script:
  - if [ "$COMPILE_AND_TEST" = "yes" ]; then
      docker pull heltai/dealii:v9.1.1-gcc-mpi
    fi

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
  - if [ "$STATIC_CHECKS" = "yes" ]; then
      python run-clang-format.py -r source &&
      python run-clang-format.py -r include
    fi
  - if [ "$COMPILE_AND_TEST" = "yes" ]; then
      docker run heltai/dealii:v9.1.1-gcc-mpi /bin/sh -c "git clone https://github.com/SGauvin/lethe && cd lethe && git checkout $BRANCH && mkdir build && cd build && cmake ../ -DCMAKE_BUILD_TYPE=Release && make -j2 && ctest -j"
    fi
 
