sudo: required

env:

compiler:
- gcc

notifications:
  email: false

language: C++

before_install:
- sudo apt-get update
- sudo apt-get install build-essential wget automake autoconf gfortran openmpi-common libopenmpi-dev cmake subversion libblas-dev liblapack-dev libblas3gf liblapack3gf libtool libboost-all-dev tcl tcl-dev environment-modules qt4-dev-tools

script: 
- git clone https://github.com/dealii/candi
- cd candi
- echo "Launching candi"
- ./candi.sh
- echo "Installation complete"
