sudo: required

env:
  - BUILD_TYPE=Release

services:
  - docker

compiler:
- gcc

notifications:
  email: false

language: C++

before_install:
- docker pull dealii/dealii:9.0.0-gcc-mpi-fulldepsspack-debugrelease

script:
- export DOCKER_RUN="docker run -P -v `pwd`:/home/dealii/app:rw dealii/dealii:9.0.0-gcc-mpi-fulldepsspack-debugrelease  /bin/sh -c"
- echo "Docker instantiated"
- $DOCKER_RUN "mkdir app/build-travis;"
- $DOCKER_RUN "ls "
- $DOCKER_RUN "cd app/build-travis;"
- $DOCKER_RUN "ls "
- $DOCKER_RUN "cmake ../ "
- $DOCKER_RUN "cd build-travis; ctest"
