sudo: required

env:

compiler:
- gcc

notifications:
  email: false

language: C++

before_install:

script: 
- git clone https://github.com/dealii/candi
- cd candi
- echo "Launching candi"
- ./candi.sh
- echo "Installation complete"
