sudo: required

env:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug

services:
  - docker

notifications:
  email: false

language: C++

before_install:
- docker pull dealii/dealii:9.0.0-gcc-mpi-fulldepsspack-debugrelease

script:
- export DOCKER_RUN="docker run -P -v `pwd`:/home/dealii/app:rw dealii/dealii:v9.0.0-gcc-mpi-fulldepsspack-debugrelease  /bin/sh -c"
- echo "Docker instantiated"
- pwd
- ls
- $DOCKER_RUN ls /home/dealii
- $DOCKER_RUN export DEAL_II_DIR=/home/dealii/
- mkdir build
- cd build
- cmake ../
- ctest
