sudo: required

env:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug

services:
  - docker

notifications:
  email: false

language: C++

before_install:
- docker pull dealii/dealii:9.0.0-gcc-mpi-fulldepsspack-debugrelease

script:
- export DOCKER_RUN="docker run -P -v `pwd`:/home/dealii/app:rw dealii/dealii:9.0.0-gcc-mpi-fulldepsspack-debugrelease  /bin/sh -c"
- echo "Docker instantiated"
- $DOCKER_RUN "test -d build-travis && rm -rf build-travis; mkdir build-travis; cd build-travis; cmake -GNinja ../; ninja"
- $DOCKER_RUN "cd build-travis; ctest -N; ctest -V"
