sudo: required

env:
  - BUILD_TYPE=Release

services:
  - docker

compiler:
- gcc

notifications:
  email: false

language: C++

before_install:
- docker build dealii/dealii:9.0.0-gcc-mpi-fulldepsspack-debugrelease

script:
- echo "Docker instantiated"
- ls
