sudo: required

dist: xenial

services:
  - docker

notifications:
  email: false

language: C++

before_install:
- docker pull dealii/dealii:v9.0.0-gcc-mpi-fulldepscandi-debugrelease

script:
- export DOCKER_RUN="docker run -P -v `pwd`:/home/dealii/app:rw dealii/dealii:v9.0.0-gcc-mpi-fulldepscandi-debugrelease  /bin/sh -c"
- $DOCKER_RUN "pwd; ls"
- $DOCKER_RUN "test -d app/build-travis && rm -rf app/build-travis; mkdir app/build-travis; cd app/build-travis; cmake -GNinja ../; ninja"
- $DOCKER_RUN "cd app/build-travis; ctest -N; ctest -V"
