sudo: required

dist: xenial

services:
  - docker

notifications:
  email: false

language: C++

before_install:
- docker pull dealii/dealii:v9.0.0-gcc-mpi-fulldepscandi-debugrelease

script:
- export DOCKER_RUN="docker run -P -v `pwd`:/home/dealii/app:rw dealii/dealii:v9.0.0-gcc-mpi-fulldepscandi-debugrelease  /bin/sh -c"
- $DOCKER_RUN "pwd; ls -la"
- $DOCKER_RUN "sudo chmod -R 777 /home/dealii/app"
- $DOCKER_RUN "pwd; ls -la"
- $DOCKER_RUN "cd app; pwd; mkdir /home/dealii/app/build-travis; cd build-travis; pwd; cmake -GNinja ../; ninja"
- $DOCKER_RUN "cd app/build-travis; ctest -N; ctest -V"
