sudo: required

env:

dist: xenial

services:

compiler:
- gcc

notifications:
  email: false

language: C++

before_install:
- sudo apt update
- sudo apt-get install trilinos-dev trilinos-all-dev

script:
- mkdir dealii
- cd dealii
- git clone https://github.com/dealii/dealii.git
- mkdir build
- cd build
- cmake ../dealii -DCMAKE_BUILD_TYPE=Debug -DDEAL_II_COMPONENT_EXAMPLES=OFF
- make -j4
