sudo: required

services:
  - docker

notifications:
  email: false

language: C++

before_install:
- docker pull dealii/dealii:v9.0.0-gcc-mpi-fulldepscandi-debugrelease

script:
- export DOCKER_RUN="docker run -P -v `pwd`:/home/dealii/app:rw dealii/dealii:v9.0.0-gcc-mpi-fulldepscandi-debugrelease  /bin/sh -c"
- $DOCKER_RUN "mkdir build; cd build; pwd; cmake ../app; make; ctest"
